name: urban-emission-model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - lightgbm
  - requests
  - plotly
  - streamlit
  - fastapi
  - uvicorn
  - jupyter
  - pip
  - pip:
    - earthengine-api
    - geopandas
    - shap